"use client";
import { useState } from "react";
import { CheckCircle2, ChevronDown, Heart, PenLine, Save, Sparkles } from "lucide-react";
import { DAILY_CHECK_IN_OPTIONS } from "@/lib/check-in-options";
import { cn } from "@/lib/utils";

type Journal = { journalContent: string; memorableMoment: string; reflectionGood: string; reflectionBetter: string; reflectionRemember: string; closedAt: Date | null };
export function DailyJournal({ date, dateKey, initial, initialMood, initialMoodNote, canReflect, summary }: { date: string; dateKey: string; initial: Journal; initialMood?: string | null; initialMoodNote?: string | null; canReflect: boolean; summary: string[] }) {
  const [form, setForm] = useState(initial); const [open, setOpen] = useState(Boolean(initial.closedAt || initial.reflectionGood || initial.reflectionBetter || initial.reflectionRemember)); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [mood, setMood] = useState(initialMood ?? "");
  const update = (key: keyof Journal, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function save(close?: boolean) { setSaving(true); setSaved(false); try { const res = await fetch("/api/daily-journal", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date, ...form, close }) }); if (!res.ok) return; if (mood) { const option = DAILY_CHECK_IN_OPTIONS.find((item) => item.mood === mood); if (option) await fetch("/api/check-ins/today", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dateKey, mood: option.mood, emoji: option.emoji, note: initialMoodNote ?? null }) }); } setSaved(true); if (close) setForm((current) => ({ ...current, closedAt: new Date() })); } finally { setSaving(false); } }
  return <div className="space-y-5"><section className="rounded-4xl border border-border bg-card p-5 shadow-[0_18px_60px_rgba(94,58,47,.055)] sm:p-6"><div className="flex items-start gap-3"><span className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-primary-soft/50 text-primary-dark"><PenLine className="size-5" /></span><div><h2 className="text-base font-black">یادداشت امروز</h2><p className="mt-1 text-xs leading-6 text-muted">امروز چه چیزی توی ذهنت هست؟</p></div></div><label className="sr-only" htmlFor="daily-note">یادداشت امروز</label><textarea id="daily-note" value={form.journalContent} onChange={(e) => update("journalContent", e.target.value)} placeholder="هنوز چیزی برای امروز ننوشته‌ای." rows={6} className="mt-5 min-h-36 w-full resize-y rounded-2xl border border-border bg-background/60 px-4 py-3 text-sm leading-7 outline-none placeholder:text-muted/70 focus:border-primary-soft focus:ring-2 focus:ring-primary/10" /><label className="mt-4 block text-xs font-black text-muted" htmlFor="daily-moment">لحظه امروز <span className="font-medium">(اختیاری)</span></label><textarea id="daily-moment" value={form.memorableMoment} onChange={(e) => update("memorableMoment", e.target.value)} placeholder="یک اتفاق، فکر یا جمله‌ای که نمی‌خواهی فراموش کنی..." rows={2} className="mt-2 w-full resize-y rounded-2xl border border-border bg-background/60 px-4 py-3 text-sm leading-7 outline-none placeholder:text-muted/70 focus:border-primary-soft focus:ring-2 focus:ring-primary/10" /><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-muted">{saving ? "در حال ذخیره..." : saved ? "ذخیره شد" : "هر زمان خواستی ذخیره کن"}</p><button type="button" onClick={() => save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-black text-white transition hover:bg-primary-dark disabled:opacity-60"><Save className="size-3.5" />ذخیره یادداشت</button></div></section>
    {canReflect && <section className="overflow-hidden rounded-4xl border border-border bg-card shadow-[0_18px_60px_rgba(94,58,47,.055)]"><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} className="flex w-full items-center justify-between gap-3 p-5 text-right sm:p-6"><span className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-gold/15 text-gold"><Heart className="size-5" /></span><span><strong className="block text-base font-black">بستن امروز</strong><span className="mt-1 block text-xs text-muted">{form.closedAt ? "امروز بسته شده؛ هنوز می‌توانی ویرایشش کنی." : "اگر دوست داری، چند خط درباره امروز بنویس."}</span></span></span><ChevronDown className={cn("size-5 text-muted transition-transform", open && "rotate-180")} /></button>{open && <div className="border-t border-border p-5 sm:p-6"><fieldset><legend className="text-sm font-black">امروز چطور گذشت؟ <span className="font-medium text-muted">(اختیاری)</span></legend><div className="mt-3 flex flex-wrap gap-2">{DAILY_CHECK_IN_OPTIONS.map((option) => <button key={option.mood} type="button" onClick={() => setMood(option.mood)} aria-pressed={mood === option.mood} className={cn("rounded-xl border px-3 py-2 text-xs font-bold transition", mood === option.mood ? "border-primary bg-primary-soft/45 text-primary-dark" : "border-border bg-background/60 text-muted hover:border-primary-soft")}>{option.emoji} {option.label}</button>)}</div></fieldset><Reflection label="چه چیزی امروز خوب پیش رفت؟" value={form.reflectionGood} onChange={(value) => update("reflectionGood", value)} /><Reflection label="چه چیزی می‌توانست بهتر باشد؟" value={form.reflectionBetter} onChange={(value) => update("reflectionBetter", value)} /><Reflection label="چه چیزی از امروز می‌خواهم یادم بماند؟" value={form.reflectionRemember} onChange={(value) => update("reflectionRemember", value)} /><div className="mt-5 flex flex-col gap-2 sm:flex-row"><button type="button" onClick={() => save(true)} disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-black text-white hover:bg-primary-dark disabled:opacity-60"><CheckCircle2 className="size-4" />{form.closedAt ? "ذخیره تغییرات" : "بستن امروز"}</button><button type="button" onClick={() => save(false)} disabled={saving} className="rounded-xl border border-border bg-background/60 px-4 py-3 text-sm font-black text-muted hover:text-primary">فقط ذخیره کن</button></div></div>}</section>}
    <section className="rounded-4xl border border-border bg-card-soft/35 p-5"><div className="flex items-center gap-3"><Sparkles className="size-5 text-primary" /><div><h2 className="font-black">امروز در خلوت</h2><p className="mt-1 text-xs text-muted">رد کوچک چیزهایی که امروز ثبت شده‌اند.</p></div></div>{summary.length ? <ul className="mt-4 space-y-2">{summary.map((item) => <li key={item} className="rounded-xl bg-card/70 px-3 py-2.5 text-sm font-bold text-foreground">{item}</li>)}</ul> : <p className="mt-4 text-sm leading-7 text-muted">امروز هنوز آرام است.</p>}</section></div>;
}
function Reflection({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="mt-5 block text-sm font-black text-foreground">{label}<textarea value={value} onChange={(e) => onChange(e.target.value)} rows={3} className="mt-2 w-full resize-y rounded-2xl border border-border bg-background/60 px-4 py-3 text-sm font-medium leading-7 outline-none focus:border-primary-soft focus:ring-2 focus:ring-primary/10" /></label>; }
